# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from credbroker.proto import credbroker_pb2 as credbroker_dot_proto_dot_credbroker__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in credbroker/proto/credbroker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CredBrokerStub:
    """Agent-facing broker API. Agents hold grant tokens, never raw credentials.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestGrant = channel.unary_unary(
                '/credbroker.v1.CredBroker/RequestGrant',
                request_serializer=credbroker_dot_proto_dot_credbroker__pb2.GrantRequest.SerializeToString,
                response_deserializer=credbroker_dot_proto_dot_credbroker__pb2.GrantResponse.FromString,
                _registered_method=True)
        self.InvokeTool = channel.unary_unary(
                '/credbroker.v1.CredBroker/InvokeTool',
                request_serializer=credbroker_dot_proto_dot_credbroker__pb2.InvokeRequest.SerializeToString,
                response_deserializer=credbroker_dot_proto_dot_credbroker__pb2.InvokeResponse.FromString,
                _registered_method=True)
        self.RevokeGrant = channel.unary_unary(
                '/credbroker.v1.CredBroker/RevokeGrant',
                request_serializer=credbroker_dot_proto_dot_credbroker__pb2.RevokeRequest.SerializeToString,
                response_deserializer=credbroker_dot_proto_dot_credbroker__pb2.RevokeResponse.FromString,
                _registered_method=True)


class CredBrokerServicer:
    """Agent-facing broker API. Agents hold grant tokens, never raw credentials.
    """

    def RequestGrant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InvokeTool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeGrant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CredBrokerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestGrant': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestGrant,
                    request_deserializer=credbroker_dot_proto_dot_credbroker__pb2.GrantRequest.FromString,
                    response_serializer=credbroker_dot_proto_dot_credbroker__pb2.GrantResponse.SerializeToString,
            ),
            'InvokeTool': grpc.unary_unary_rpc_method_handler(
                    servicer.InvokeTool,
                    request_deserializer=credbroker_dot_proto_dot_credbroker__pb2.InvokeRequest.FromString,
                    response_serializer=credbroker_dot_proto_dot_credbroker__pb2.InvokeResponse.SerializeToString,
            ),
            'RevokeGrant': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeGrant,
                    request_deserializer=credbroker_dot_proto_dot_credbroker__pb2.RevokeRequest.FromString,
                    response_serializer=credbroker_dot_proto_dot_credbroker__pb2.RevokeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'credbroker.v1.CredBroker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('credbroker.v1.CredBroker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CredBroker:
    """Agent-facing broker API. Agents hold grant tokens, never raw credentials.
    """

    @staticmethod
    def RequestGrant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/credbroker.v1.CredBroker/RequestGrant',
            credbroker_dot_proto_dot_credbroker__pb2.GrantRequest.SerializeToString,
            credbroker_dot_proto_dot_credbroker__pb2.GrantResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InvokeTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/credbroker.v1.CredBroker/InvokeTool',
            credbroker_dot_proto_dot_credbroker__pb2.InvokeRequest.SerializeToString,
            credbroker_dot_proto_dot_credbroker__pb2.InvokeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeGrant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/credbroker.v1.CredBroker/RevokeGrant',
            credbroker_dot_proto_dot_credbroker__pb2.RevokeRequest.SerializeToString,
            credbroker_dot_proto_dot_credbroker__pb2.RevokeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
