# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: credbroker/proto/credbroker.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'credbroker/proto/credbroker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!credbroker/proto/credbroker.proto\x12\rcredbroker.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"L\n\x0cGrantRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x11\n\ttool_name\x18\x02 \x01(\t\x12\x17\n\x0frequested_scope\x18\x03 \x01(\t\"f\n\rGrantResponse\x12\x13\n\x0bgrant_token\x18\x01 \x01(\t\x12.\n\nexpires_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08grant_id\x18\x03 \x01(\t\"|\n\rInvokeRequest\x12\x13\n\x0bgrant_token\x18\x01 \x01(\t\x12\x11\n\ttool_name\x18\x02 \x01(\t\x12*\n\targuments\x18\x03 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x17\n\x0fidempotency_key\x18\x04 \x01(\t\"I\n\x0eInvokeResponse\x12\'\n\x06result\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x0e\n\x06status\x18\x02 \x01(\t\"!\n\rRevokeRequest\x12\x10\n\x08grant_id\x18\x01 \x01(\t\"!\n\x0eRevokeResponse\x12\x0f\n\x07revoked\x18\x01 \x01(\x08\x32\xee\x01\n\nCredBroker\x12I\n\x0cRequestGrant\x12\x1b.credbroker.v1.GrantRequest\x1a\x1c.credbroker.v1.GrantResponse\x12I\n\nInvokeTool\x12\x1c.credbroker.v1.InvokeRequest\x1a\x1d.credbroker.v1.InvokeResponse\x12J\n\x0bRevokeGrant\x12\x1c.credbroker.v1.RevokeRequest\x1a\x1d.credbroker.v1.RevokeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'credbroker.proto.credbroker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GRANTREQUEST']._serialized_start=115
  _globals['_GRANTREQUEST']._serialized_end=191
  _globals['_GRANTRESPONSE']._serialized_start=193
  _globals['_GRANTRESPONSE']._serialized_end=295
  _globals['_INVOKEREQUEST']._serialized_start=297
  _globals['_INVOKEREQUEST']._serialized_end=421
  _globals['_INVOKERESPONSE']._serialized_start=423
  _globals['_INVOKERESPONSE']._serialized_end=496
  _globals['_REVOKEREQUEST']._serialized_start=498
  _globals['_REVOKEREQUEST']._serialized_end=531
  _globals['_REVOKERESPONSE']._serialized_start=533
  _globals['_REVOKERESPONSE']._serialized_end=566
  _globals['_CREDBROKER']._serialized_start=569
  _globals['_CREDBROKER']._serialized_end=807
# @@protoc_insertion_point(module_scope)
